name: Templar_Industries
main: me.PsionicTemplar.templarIndustries.Start
version: 0.1
author: PsionicTemplar
description: Industrialized Vanilla Mincraft!
commands:
  test:
    description: Does whatever I want it to...